version: '3.8'

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/acosi/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/acosi/data/wordpress
      o: bind

services:
  nginx:
    build: 
      context: requirements/nginx/
      args:
        USER: ${LOGIN}
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always
    env_file: .env

  mariadb:
    build: 
      context: requirements/mariadb/
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always
    env_file: .env

  wordpress:
    build: 
      context: requirements/wordpress/
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
    env_file: .env